import timeit
import modularity1
import modularity2


setup_ioc_1 = """
@INTERFACE_ID
class IOne(ModuleExportInterface): ...
class One(IOne): ...
ioc().registerExport("One", One())

@INTERFACE_ID
class ITwo(ModuleExportInterface): ...
class Two(ITwo): ...
ioc().registerExport("Two", Two())

@INTERFACE_ID
class IThree(ModuleExportInterface): ...
class Three(IThree): ...
ioc().registerExport("Three", Three())

@INTERFACE_ID
class IFour(ModuleExportInterface): ...
class Four(IFour): ...
ioc().registerExport("Four", Four())

@INTERFACE_ID
class IFive(ModuleExportInterface): ...
class Five(IFive): ...
ioc().registerExport("Five", Five())

def test():
    ioc().resolve("One", "", One())
"""

setup_ioc_2 = """
class IOne(ModuleInterface): ...
class One(IOne): ...
ioc().register(One, One())

class ITwo(ModuleInterface): ...
class Two(ITwo): ...
ioc().register(Two, Two())

class IThree(ModuleInterface): ...
class Three(IThree): ...
ioc().register(Three, Three())

class IFour(ModuleInterface): ...
class Four(IFour): ...
ioc().register(Four, Four())

class IFive(ModuleInterface): ...
class Five(IFive): ...
ioc().register(Five, Five())

def test():
    ioc().resolve(IOne)
"""

time_1 = timeit.timeit("test()", setup=setup_ioc_1, number=1_000_000, globals=modularity1.__dict__)
time_2 = timeit.timeit("test()", setup=setup_ioc_2, number=1_000_000, globals=modularity2.__dict__)

print(f"ioc 1 time: {time_1}")
print(f"ico 2 time: {time_2}")
